project:
  type: website

website:
  title: "Soccer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: convex.qmd
        text: Convex Hull
      - href: about.qmd
        text: About
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



